name: Node.js CI

on: [pull_request]

jobs:
  check_changed_folders:
    name: Check files
    outputs:
      run_container: ${{ steps.check_files.outputs.run_container }}
      run_hometown: ${{ steps.check_files.outputs.run_hometown }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt

          echo "::set-output name=run_container::false"
          echo "::set-output name=run_hometown::false"

          while IFS= read -r file
          do
            if [[ $file == container/* ]]; then
              echo "::set-output name=run_container::true"
            fi
            if [[ $file == hometown/* ]]; then
              echo "::set-output name=run_hometown::true"
            fi
          done < files.txt

  find_pr:
    name: Get PR number
    needs: check_changed_folders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - run: echo PR is ${PR}
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
    outputs:
      pr: ${{ steps.findPr.outputs.pr }}

  container_job:
    name: Deploy Container MFE
    needs: find_pr
    if: needs.check_changed_folders.outputs.run_container == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install CDK dependencies
        run: npm --prefix container/cdk install

      - name: Configure AWS credentials
        env:
          AWS_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure --profile default set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure --profile default set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure --profile default set region "$AWS_REGION"

      - name: Deploy
        run: 'npm --prefix container/cdk run deploy pr${{needs.find_pr.outputs.pr}}'

  hometown_job:
    name: Deploy Hometown MFE
    needs: find_pr
    if: needs.check_changed_folders.outputs.run_hometown == 'true'
    runs-on: ubuntu-latest
    # env:
    #   AWS_DEFAULT_REGION: us-west-2
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install CDK dependencies
        run: npm --prefix hometown/cdk install

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          working_dir: 'hometown/cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: 'arn:aws:iam::586890172263:role/testing-role-Role-1W2U5EHSZS9D1'
          role-session-name: CDKDeploySession
          aws-region: 'us-west-2'

      - name: Deploy
        run: 'npm --prefix hometown/cdk run deploy pr${{needs.find_pr.outputs.pr}}'
